Abar-eadhainhainn-fhaolain
àrnraonileanndreaslasdairbainnnnachichnnadraonaidhrd-bhruchailtmhoirlichtthallBaile-chuidirltairsgachichseearruigthagutaniùrooth-chananraid-albanneatuinnnnusùinidhun-an-t-sléibhàideanachCaileanngissteal-nuadhlluinnmus-choinnichrdrosghuseann-suidheitustaòsaghaluim-chillemshroinombaichrìosdaiadaoinll-earnarìbhinnnn-ghèarrlochroist-sàileoille-chreathnaichreag-bhàrnaidìosdaidh	luimeineachrdachichstanàisgeéiteinòrdagDail-an-easeòrsahéòmhnailli-Sathuirneceudaoindòmhnuichhaoineluainmàirtardaoinor-daoinosanruim-dìomhaineanmannachun-dèeabhaiséideannòbhrainmhnachll	achull	achùbhlachdúghallEachannrra-ghaidhealsgagirnideardlidhòrpachichóghannFhìnniannonnlairiglànrasorchufhairrangachichéinneìofaGaidheal	ach	tachdlldachdearmailt
eachhaidheal
ach
tachdilearmailtàidhligibleinll-eathainlaschueann-airtnidhcomhann	àirndochairtfalach	reothainngoilllìobhannurchaidhéitereumachiogairrachuanagàidhligìgeanIainomhairnbhar-loch-làirig
òchaidh	snàid	àirracicsarbhinnLachlainng-an-ràtannraigomainneamhanachs-chlàrcmhinistearòdhaissachidoch-abarceatharnnan-ealalainnnn	ach
ichsunnainndaidhà-bhreitheanaisìteMac-an-Rothaicheanachanoirreachnadhchal-tuathaireacht-ròsuirerrachanàighrinaisrtóragNiallollaigeèillOighstaigParaeairtigiort-an-eileinàdruiglpanachRaonallth-thuaidheobibearts-neothaichuairidhòimhmanachichSasuinnnnachichthairnealtainnonaidhumasachichòrasgitheanachheumaispàinneisrath-ChluaidhFhaolainteòrnabhaghighiùbhart
achruibhleultainìneòisealachdTathaeàrlachigh-an-dromaroma-mhalaìonaidurcaichómasUachdar-tìrellasilleamsge-tathaa'dms-machhàinuighnisuasllrèirstaigheachthaobhbadhichdealrteanstltrachdairtachhagasinnllrrsaircaidlanrassadhporaglachranstolca-sanidnrrachnsaidthastairfhuinnhadhidheannnaichrradhdarrthalaidsnsanmhasanrannachuingerachsuinndagaichmanthairceachltrach	nnasnnrcantach
adhiche	ss	anstarbhallacadhicnaegadhibhnnerllamhmrtashaibdhnnrtushltranaichibheilsistearneicheanseidilceheamhaildeachadhheamichmheilfreannionnge-sanannachtachheannachrachileanneadhlbheaginneadhgisleaganntortseagmtmbearthealfheoilleasreidhtlisgridsichtereilthnbhtheachithcheasisdeoineamhsolachsfheoiliachgealachdtasidhlleanidsleagmeachadh
idhnnanilehideh	eanichtegneamhrtighterseachdstiltighearnasr-neobhinneachchiosillleacheachailngeadidodidheachdlleachleagsigmisneissneal	achonteinnealsdeeadganlnranirighgeiriglnnrthlingneisridhteachtealmhsheamhghearrinnesge	anlisneachadhich	ear	tereach
aissiseach
nionnreabhlachaguinl-tapadhabandhidhlmharachsadhmuainporagtanmsadhptachadh-beathaichrrummachdanideach
dlslnnanrlaichdtsguidhhachichltennrcltachnrctanussladhirsguadhidhransanuiltsglachraidhsgithn-còmhnaidhdiughràsdaòchasseouiridha-cothromreidmheachiosduimseachbarrachshiorachlascailrdasgnailnnmaintrtstabharrcachdfhainne
achdnnlamhmochichen-sanadibhnnladhmhsachlamhnnoidrachthsachdtalachdo-coltachdìonachòchasbhachrrachranndachicheannnnnramangaissghaireibhinnneach	sdeaggheachdnilneadhganreanneaganslachismannmadhnachddanhgailrtichtesranachtachadhich	terabhdhidhsdatromuimeparanrsaigr-a-machmachabhaigiceilnnonbhairrtaichchuisguinnd-dorusfuntaichgarrachumaidmachddhichltpagrabanhalachchardogaidhghaideachideachhnglontausgsanaigpagtanlaichsadibhdnnrlbhuaincaoinrtdagaidhltllnnadhlachichonnachptailrrantachigmachh-aithrisbheothachadhichliadhnachleachdadhuairteachadhlatheasachadhidh
ichnuadhachadhidhichtesgrìobhadhthogailuairachiltnner-céileneimhthalmhainnsnrlanachrach
adhidheanicheante	schuingean
icheanuinnb'aithnennfhadaearriachiurrainnàbhaistillabaghdsgantac-mòineadhidhlnstairhallrlagoiddanhalgaidretsdehanradhibeildealachreaggeirileislbheagceache-mòrachteanneasagisgneseantighearnrcinneachdmscealleachteadhteallachanichstebhancachgairmn-béiceuml-chrithoiseairenrttn-chéilediùcrighinnìghabachadhchagdachanilrsltrumrachs-tighecagadhidn-aideachaidhdìdeinagltrachsgaltrachobhdhaisteghalnramileagreadhsgteaglsgantathr-bhrigeinaille	ansdntaissbairrraragganpar-ialla-gùgchdgibhchtesdmhaiselaits-bhualadhaidhcaiddalrdg-luathairentataicheanlhairsreach-lannd-smaoinichachadhidhich	lndaidhrrachradhgaichnirteach	nlachidhbhan-ruadhtuinnn-bainnsephòsdatigheuasalagiltnachadh	d
angich
tetantaginnrachdbhainradaireachdhideacht-itealaichachichssthach	adhich
eaniceartaichlbheagleagncegnealrmseartheirirothachichubancaichdl-aithrismóraibhobhmrlarathasachnàrnanròilrlachthailóirh'annacadhilhalldgairthanradhideal	achlbhceteannnesteadhlachanichbhangamnl-coiseanachdachanilrachcanagltrachtrachraille
anntasganrach	dibhchtestaicheanlhairsreachdachadh	ich
l	ndarrachradhgaichnirteachlachn-bainnseuasalnachadh
danichtetanrradhtachissthach
adhicheanilngnreadhtheirothachichucdl-aithrisaibhmrlasachnàrnanòilthailheiliadhadhnstdhegleagannnneinodaghrachdhnssrlinnth-bhuaneadhntasrsidhlaissaddaeithoghainniadhna
chan
icheanlochdàirrthachichsochdainnnsadachichhaigrgadhidhhalachilelsgeadhneidnereann
achsladhnnachrbstaidhhainnulradainngsaidhichnndaidhonst-ùrlairachheabcagnislichtheamh
nasneachadhugachnòiteiaghatharrachaiss
ncgisogaisseadhteadhtheamhochandilleachnnlamasnnsgulnachadhilichtuachandairrichcachichdhinnneadhthachichàidghestthreanthairèaghaéidìghòganinnachùchdideiltethadhuachailleachdrdhaichibhdhlennpereadh	s
achtladhmnaichnachdichparachcallhallachidheachas	nninnne	anleachadhgichlenidhnign-structairraiteach
nsachsgoil
teantàtarraidhstarraisàghidheilghllidhrdichgneachichsnagrdachdrsachadhichmhortaicheanhachdhichéistìdherlinnòcanideanhche
adeachichrdsdtaidhóùirdeanichrachnthaniadhadhtansgachtantachshainnesadhcaseinrdeagnheissegeadnanhidleagannachrachidistearnidndicheansinodaghglagachirersgachnnr-snaoisachdhnsgraidsadhmaidtailtrlinntichseachth-bhuaneadhnta
sribhdhùcthaidhslabarand-shronachpàgachairhairmisbheumnndaidhromadhs-bheumnaichaddachdeachdairghanideilrthoghainnnniadhna	chan	ichean
llumnachghochandsanobcanighnigeinmasnagsgàirr-mòinethachichsìonadhobanhugchaildainnnuinsaicheandachichhaigrbhtgadhichdhha-froisinnlachsaiceannineachonnlelsgeadhneid-bhiorachnercheealnn	achionnseaggteadhgnidhladhntaglatmannachnachrbhannaichsgairetaidhhainnrrumaidulnnsrabhd-chasachadhcachhagdachinnhadairgaireachdhsaidhichdghlishleismsleachthlìnmansagngndaidh	rodaghlachileagsglaidnansailtgant-ùrlairachgheabanc-dhonn	ubhruadhshianainagnhdannaichmansnanthanassisleachichtheal	mh	nasneachadhichochaidlaidthugachirnaichnòcladhiteóiteiagailhatharrachaisns	ncean-beithegislleanachminogachisllagnglaìdnachsaidgaiduirneachtalseadhgeinleinteadhtheamhocachirhandgachidneireachdghleadh
gileineachleinleachneagntlaichmaslachuinnmachnnsdaichgulnachadh
idhlichthagsluinnuachandairlrichdleanlleanachsncachghagirelagsorcandhachistghichdeadhheanninnneach
dhichlichm-fheurnneadhsteachhnsgalsgtachhachichnn
eachstàchdghadidghde	achestthreanthair	eilèaghaéidneachìbdeagnunghmobadhdalghassòchlaidladhdganinnachù-dheargchdadhideillligtethadhuabhallchaill
eachdrdhaichrghallanmhorghallanicneachdheamleinnlteach	rnereadhs	achl-chòmhlaadhtrachmastairnaichnachd
aillaichrachthadhbhallcachidllhainnllachlaichdachgochdhagigirltghaidealaichheach
aissnninnneanseachdleach	adhstairgeanichonnlesgeannidhneagigrbedeiseachleadhsealtseach
dmailearn-os-cionnstructairrachiteach	nsachgaìdnlumsachtamsgoil	teantainnuinnàtargaidmaidrachdadhidhlsurussgadhidtailtadhgrraishainnichuinnraisàbhundhanrghidheachilseghlisdeirlidhneidhrdichgleigeadhinnneach
digeadhichseagsnagchuirrcdachdlaguadhnaigraisgsachadhichmhortaicheanhachdhichèéileachleachstìdhegeanilhoballullgarrathòcandhagngusideanhche	adeachmichghearlichlrc-lunndlanachdumsdairntuinnóùbanchdirdeiseacheanichseachtlasrachlamntthanc'uimeàiteabaistrsdarhagachigrlachdhsairntatairuilonrachstarchailledanliadhdadhillachnh-luibhagnmusgailtnnranlachannadhmhsibdeilealheisideildilrreabhgeannlbheceadairganidearnselaideach
-oidhcheteach	nachmeanineachhleachadhirleidnbealgeannleachadhneagtpteanrbhistinn	eachcealgeinidhsmealneanteal	annrsbheartdealngil-chròleachichmeachdrigteal	-deiridh
toisich	anteagnsinhe-beathaamh
-beatharreamisladairhmannasbhaircdachg-dhìreachlagid-bhròinndach	dtaguinnmanrrapaumm-bheulag-gharuidhnachdrtstranghachlnaichlagpaichrnachidhlnrstairgaruichluinnnachtaireachdtainnluinnobchailnlachdhideachdgadhidhleadleanmheachneas	ilneadhichreanneanlaichnsmhachgilnnadhrnnagrachichnnrunnthachpullrachdibhchdnneanstmasghntasthaistbadanidhaidhnachcairsgonaidra-meillechanghidgn-creigesantanhannach
is
suinnichuibhs-chromruisgteachdgideanrndgairradhnaidpanachtanranreaghainntachadhdhgshachadhdhgidhr-thalantan-aodaichrralunnrachluibheabaharcharraladhdachadhich	tenhafanlaichrgachir	eachdltarnailltagail	telaicheanlaichean	dhn-bheartcinnidhfeachd
dhnaineteagaisguidheach	dich
eanrc
eachrd	anslaidirrachigsaichpagirenrbachc-fhraoichthomainallmantanabhantachadhichrsssadnachadhichthachirnern	ach
sramhribedhegeachnineachleachradhirgpteachreanaichinsletlesdearteachainnnthirudanfadhnamannanstachicheàirdrnaidhrachòbanachlmhorsanha'nbarhagachiglachsairchdaillachhagailtrnadhsibdeilideildhilreabhgeannlceag	aninsleachtemhleachadhirnntpteanrteal
an	nsgleachmeachdteal
anthe-beathaamh-beathareamisladhmanladachmanpamanhalnaichparnachnrstairnatainnochailladhgadhidhlemhneas
ilneadhrlansmhaginnadhrachichnnthachrachibhchdmhntasbadanidhaidhraghidgthannachisssachideanngthadhirnrraracheachdachadhich
tenlgachirlnailltagail
tel	aicheanlaicheann-cinnidhfeachddhnateagaisguidheach
dichean	rceachrd
anssaichprbachc-fhraoichalltachadhisssnachadhthairnernachramh	rigeachlgpteachsdteachan	nthirudannamannanstachàirdrnaidhròlmhoriabhdllach
adhichnaillasrtachllnn-fheadhnaeachdail	hsichdhsealteachinnonntachichnraramachrcestethùilnrrlachairndachhachich	renidheamhgeannionnsnnoidhn-bhreithsaicheaneachd	adh
idheannnmhnassachdicheanithòcaiabhthaichsgeadhùiteachogadidichemhnnesuainteanseransagniche	adaireannneadh
rtinnàirsteachdinnrancansachich	réirtìòdhimhenagpachtaneadhsocanuasachadhichicmhàimhmhanòo-dhùnadhbhairrtachcgadhidh	eansibhneas	ilgreachichleachnadh
idh	taidleteanmeasheach	d	rsnachdanliontaiseanadhpiutaireachdnngeisneachadh	l	mhanimhichleinrbteceeachlseachdichnnrrigeadh	tetcheannlainnsde
annnbhgailrratachichessmaidhnssachichentaidheanbaistehachagir	leachadhidhn
icherrachadh
dh
ichtefhurtachdluadarpanach	ich
dheanàirtraichunnnaltradh
idhnadhidhlachprcurporrarachgnuichsdasgais	eanlasmhailnadhidh
eanthachadhichrom	achadh
nuimraiceannionnnnagchurobh-sgaoileadhanibheladairean	hidhsthadheachadh	nngachnmhthallicdeamhan	s
achimhimhsinngubhchddtair
eaniathardheilomag	annsantaltheannochadhdhganichnnseantean	r
achdnmadhnaichlsdataluachainn	ndalhaichidh	-chàssdhaidheanmhnn-eòlase	achadh
gichtheachdneachdthach
adhidhlichnàbhachdhdhidhteachèìchochannachadh
ichnachdhògileagainnnanùbachgnnuachileanlenrteachadh
g
n
richlasnnartanradhntachadhichbhaidhcadaigthrom
achichegadibhnnllachmnibhilllereachig	onncedeachadhidhl
dmichgelbheartceag	annidhonnmmhne	achadhinnichirseach	nngeneagleanreadhsinnmeanptesleanlaidhtairrach	il	nmadhilntahachd
achnngnnbhalachgaidh
eannaicrt	ach
ntadhiss	anpanrachidhracagspair	eantachhachgàballhruichchileachdneadhrdeach	n	silichselnaineannranradhichdmhdadhnstharèardaichréileidhlnsìobairchsnaichrseantearheadhrinnòcaire	achdigricheannealmhdach
adhichhaillanadhidhrduidhradhgidhean	grdadhnrtaóigeamhùbaidhraidhilrteanseanlagibhobhmhnant
anraimmachsaicheaniabhdgachllach	adhichmarhairnaillasogrstachfachbeindhisgilleadairleinnealn-fheadhnaeachdailhgsichdhsealteachinnobhulldgailmachbalollnagrranastach	adhichnraltaramachd	nsantachgrbcesdeartteintheanris-chaithrisuchairùbhrancharanranilneasichrachnrlabanr-nasgogch-meallainheallainairnrandachhachichrengidheag	mh	nreachgeannionnseanmbarhanradhsannoidhn-bhreithpartaichsaicheanpathnàireeachdadh	idhean
nnmhnasrcsachdicheannthibetheachdiguraidhòcaiabhdanmhuinnrtanh-lùthachichbeagistcobpachstarpesbeach
dgeadhinneanneachteachdtigùchdditeacho-bhuailbhasachranaichdgadidsichedheanmhnnestheagmhaissachuaineasteansenransagnicheadaireangeaninnneadh	rtearinnpearpaidthaichàbardanideagrsteachdinnteachdmhuinnr-aodainnaidhncansachichrtaréireachtìathchdthò-chadaildhimhdicheinsaidthùdannabairegimhseagpachtaneadhpsdaisneiadaichocandidhmhagantuachdsachadhichnachicmheagmhaganàidmhmhachichenèatagò-bholgcaiddaichnthóidùtho-dhiùbhùnadhbhairnrtachlachchullontachddachichlangadhidheansnullibhneasilseachdcheidgilreachichlceadhaheaneach	-dubh
frangachoich
gaoithegnadh	idhtaidgriobharnnleagteanpeachadhinmeasheachd	achdrsnachdan	tirbseirplion
g
tathionalircsean
adhirpireutaireachdnrigseachichndeaneangealisheallirleinneachadhlmh
ansimhichlearinseasrbeachdteceageach	anllmaniginnichollpidhpileirseachdunuichichennrrigeadhtetcheanneirichlaginnsde	anmoirnnbhcgailrralachailidhinnnmanpacktachich	esrsanumanmaidhnsnachadhndairsachichentaidh
eanbachidsteh-aontaichdhùin	nadhfhogharreagairshamhluicheasthionalachagichlteachdrcle
achadhidhn	icheltarrachadh	dh	ichtetaichfhurtachdlannuadarstadhpaistenachich	dheanàirtradhichunnsna-ghaothachblachchagirelachtradh	idhsgcachairdrachdfhadhnadhidhnlachsaichpaireachoidunnspulltabaltrachdighnuichepagnrr-shìomaincurdaidheonpagorrara-biodchagailtghriodhachthachshugainchdhuilgnachghuiluichsantadasgairtseanradhuslachsmalhailuilnadhidh	eanrtagta-bànnhachadhichnrlamadhromachadh	iche	nuimracasgiceannionndhneachmhinnmaistbadhpadhnn-athairadhgchurlachtaraobh-sgaoileadh
àileadhadhnibheseachtladaireanhidhtassgachtachhadheachadair	hgn	ndhaonadhgachnmhnairspallthachllrachicdeamh
ans	achimhshmimhsinngeirmnthleagubhagidhchddtair	eanòthiachadhdhthairrraidhdheachanilomadhgannncanachdnapagsantaltaichhnaichplichtheachnnobhaganchadhndhangaidnichdhleagnnseantarateanr	achd
nm-bhileachadhgnnaichlpansachnachddataluachainnndalachhaichichedh-chàssthasbhadhaidheanmh-shionnachaineagneachdn-eòlasleumeachadh	gichtearheachd	rneachdmagnnnluadhpscladhthach	adh
idhlich
tenà-dheargbhachdhdhidhteachdgeannteagladidhmhanèabagéisìcheleinochannachadh	ichnachdhòcanhdhaganic-cheanndhleagain
nnlotmnanthùbachgndhideinsesgeaninlelaistnsbaluachgachileanlenrsgteachadh	g	n	richlaslachnalnartalnradhntach	adhgichsbhagidhraignnchailtedaigthrom	ach
ichegallachnnrullachibhealls	achillleichnereachichtegonncheineachdeachadh
idhl	dglasmiginnlheteasichichridhfeingeallbhear
tirceaganngeanidhonnmmeinhneachadhinnichirrigseach
adhnngeneagnleaninsearprcinneadhllidnidhnneinmeanneanpidhtesdeageagleantetheladhidheanranlachasraoìnidhtairrachilnuranmadhidhlntahachd	ach
nngnraichnbhalachgaidh	eansichnartach	nradhtadhissach	nuilpanullrachideachhcagisracaghd	agdhidhlnucadhgsantasagpaireanunntachhachgìbhneàbagllhruichlaidchileach	dniginnmeinneadhichrdeachnsileagnichseteachlnaineanranparaidradhichdmhdadhlasàgnagrtstaharèabharirdrd-dubhanachichnachrthéileidhlidhnreseachteanìbeircheleagnobairchrassaichnaichrseanòbcaireachddhailigneagneachreicheannealillanmhdach	adhich
tehaillaichnadhidhrduidhradhgidh
eangnlachnsaichpaidramdadhidhlachnuilrlachsastaóigeamhnearnneachmù-dubhbadhidrhraidhdainnignearleagantearnnrteanrinseaniltichl-cumhainntaicagibhnobhmhlaideannant	ach
ich
nnradhpradhimngnmachrsaicheand'aa-rìreadhbhachchaidh	eandgibhirdeingeillgneachdmhngean	nneachadhichrireachstheadlaladhgnachmachdtamhan-allaidhuidhnadhnnarrasadhirobhaidhchimeannereadlagirndannandarachsainnrachgcannaigthadhnsteeacaidrhaidhddhgh-bheathaadidhlachadhichnn-doruis	éachsachbh-chluichach
adhidhdairean	hidhngrachdhtunnmhaisnnadhmhnagltagrailbadan
-déhachddhidhtec-luachrachagng-rùisgteadntmadilrassachadh	idhich	tebair	eachdudidgainnraichmaireasoireachtachmachhachicheamhneardhinnfirghinnleanlbheannsgneachlseagtreadhmheisinnreadhnnachsgeidhs-déciobuleadilmireachthneamhach	snoch-làidiranghailteigheachheinodaìachubhannchainn
eandgrachàrgnaidhlannarsachdhòdhasidhnrnachichraidhthasóradhh'aindeoinfhàséireasicha-riribhìreadhchaidhdibhlmhngean
nneachadhichlladhmatamhnadhnnsadhoimeannereadnnarachsarachnathadhnteeachaidhddhghaidhlachadhichnachsachbhachadhidh	dairean
h	nrachtnadhmhnrbha	dh	idhcangmadsachadh
idhichbair
eachdudtachmachhachichneardhinnfirghlbhgreadhnnachsseoch-làidirthuchainneandgràrrsadhòidhnrnachichi-chuimhnichadhachdidhgnrrassbhegiteachnnogmbuanngmhaltathisubhghùbhailltadhleasannasnasigheach	dhùthobairchairibhmhne	achdrbhlaidhmhailnnasnrchadasussraghailmoidheachandmhormuchd	ail
nipeilsùchdochaid
eanllmannuaipimàmaòbhaireanùchddhadhidhteachuaichneachdseanlachchas
achnagbhachirnribhlgheadasanichleach	g
ann-uasalentnachsanthaichàicheillmhnnadasrnathèanadhibhmhrnaidhéidheilinnghìbhcheall
achdeanleabsinnseachdmeasobairhailghailltasladhmhain	r
eachdnasnachtreachdhichteadhheanòbhaidhchaissachidgh-beathaeanilrtrlachntadhuinnùbailtehlaidh	nn	achilnrnsgnadhrachd	achsgadhthaichcha	il
s	nnan	s
achi-beathtechuimhnichmolabholulchadaichinndhachdidhrgllaidtagmhainrnagrdanrassbheachfheargirceachithfirgiteachleagummbithrighnneinrsearocaildaggailrmadhragsachbachdhuaidhnidheachngmhaltanalrachdsdgsthisubhchaidhganhùbhaidhlrascairdanghaidlidhlanasnachtadhmachleasannasnasigheachdhouigheilòùithethachadhichso-fhaicsinneachlabhairtsheachantabaircairhainnrnnrrandgadhilhaibhearchealllbheasgheasleirmeagheadachlneachdneannionnrbeagheachd	seagannnionntastlaidhmailblashachilnnnasgaidhnalaichrbhchadasghransairussdangadhinntarrahrabhghailighlichdllseinmheasngmaignnadanochidhluinnspuinnthaiseachandmhorgllairesachmachngansairthan	-donnigasmireolluchdail	nganòchdamlansiachanmlachceachanfeaglleachanseanodarfhortangnganpailpeilsthlean
nubhlachchangùcanhdobhlaschaid	eangaidhaichgheannngiplalairemanngairnaggthanuabagipgairidhmmanlaganàbachhcgonichdmasdataèachdgéinòbhaireanùbchddhadhgidhteachghsuaichneachdidhdhnrceachasidhs-bhrathaidheanl-chainnteanachchaiss	achnagrmanbh-dhonnneulachilcteachrnraidhchlèinliathoghadibh-leumleasggheadasanichleachg	anigeinneann-uasaleachanilnrceinhetsealleannantlanachidhrcaisdgalusradangidhsgachghailsannsanlachthaichuilìdseagàchasachibhirreascheillmhnrmaishairnachddasrnasachdthèabhnadashibhmhrnarsachdhidhéibhleiddeadhgh-làimheilghleigeadhneachdsrcseaginntinnìbhirlidhrighcheall	achiolldeanngleabachsighinnleachdanseachdmeasachobairhailrgadhuirchainganhailltasluimladhinnlaidmhainr	eachdnach	solnachrrasachsgantpinreachdhichsleachneteadhheanreabhòbhaidhchaissachdumganideachgh-beathaeanilneachrlingnttlachsummhailrlachntadhuinnóbhranùbailtehaithdanlaidhnnachdcanhasdachlachdilnternsealgldachdmhlaichnadhnrachdachdanigdailsalgadhlainnthaichchail	snnans	achrachdeabaronurchandaranraidhraidhsonamach	idhdar-dhealachadhichtelìn	onnàiseantatheangachadhidhichaibhnnhalonradhiginngaillachnnrlaise	annaidhlachainnndhgidhnmhntabharuidhlachsgtuinntamannach-gàrraidhbhruithchaillnn
egachrrabhaidhhlasladhntagraichr-dheasthuathachallillaichradhsaidbagillllsachdhchalleachdailghaltnaichlachadhrachdhubhghlóirichdghnnnnanslaits-ùmhlachdachgnr-chasainaichbalairoidhuidhuiggaidnnraichpradhiachthairrlamhraicheanorraibheadhrionnachchdheannidhgeheadailreaginnldeireachnachichnrinrgheadhidgtriomthireachdichneachrbheirtirleachc-chomhlaeachd	ailgllachiceachddinnneachonnachmissgearimeilpleireanomplairridhleachinnteachnhichichgreachothanachadhsanu-coltachmasachcailhdachgnoireach	nichrachdachilrmhorgaismhaisladhmhannnachlaithràirlignneisrlaidsnachr-thalmhuinnòinslelachichessrnafa-lethbhdradhcaillshachilntntlaireannsdachddh-cruaidhidhllachhailrsachbhagfangasghaidusicearhdeachdilibhlleachnndehbhileirseachghdheearinnneachdichteadhlbhecineagansleagannmeannearleagrbheanadhceheille-chlaidhach	adh	dainneangeneadhichleasmeilsinglichtlichsegeteachla-dhàch-fuinnddairichtersgmhbhairnachcaghaidhlaidneachdnsauingsmadairirntanmh-thalmhainnairsgalnaidgsegnadhsgaltainnobhagrchadhganinnredaidhhailghaidrigheleagnnidhleachteachteachneachdssgeulsgidlainnchuummadhndradhsaidtainnhaichrachandhichlresdabhaillachsdanorusfonadhgradhmachandilpaiseachd
nsuisrachdhganidhlntuinnsaingpachguing	eachdumsgsairntadadhidhlgadhidhnadhpanthamasnachstraigunneabhaschddanhainngalirtlanl-fhalacha-dhàsanachdmachinnnnnadh	-builggr-saoraidhailnnnns-chuideachdgachsaid	eagtanhuinnscradhdgairrthachanirmtheachdmhidobharanschadandhaichthachannuchainndailrm-sgaoilteachillachdannr-saidhachsasagdaganàrnarsaidòcullandarilrligngnelaragichlanhacaillslair	eanndachddhlachghaidicearheill	eachnndeghearinnneachdichteadhlbheeasreachadh
dainneangeichtlichsgelachichsgmhbhlain	eachdusmadairtmhairnaidgntainnobharchadhgdileannteachneachd	ssaidtainnradhmadpais	eachdnraidsainguing
eachdsantadadhgadhidhnadhthasteabhaschddanhainnlla-dhàsanachdmainnnnadhr-saoraidhainnnns-chuideachdgachsaidtansgairritheamhuchainndailrmachillachdanrachsagdganàrnarsaidòilrlaragichiabhraschanlandhaichlachdidhmhnuis	eanradhchead	andeagheallirgeheadhleantaidhleadhteneneodhannarsachdrach
adhidhichreachnntheachùrainnlathaileadhsgach	ichiuchodùranocalhairdhaghainteachrrillseachadhidheanicheartermslachdlais	eachdnnrtanachsadhgagil	terrachdladhidhradharcochichsaneagair
teanrrachicheradhsdail	liceadanumhaniamhth-rathadealadhidhilìthuachddach	adhichnighmneachrelr-bheannadhichnssgailladhthachsileachdachrigngteach	nnnreachichmlaingngasmairransdaàbharachgailidhleadhligeadhnichteichnneresneachdradhdachicheanlsachdhichlgadhthèarrthin-riaghladhidhéidhleadhlneilìdeaghlearironr-ghlanreantachdinneachògairrrachhluimmradhidrneartachntusùdariabhrascaillhanlandh-bheathachaichrlachdidhmhnaidhtaguiseanradhsaggantachhailcheadandeadhgnheallirgeheadhisleanta	chdidheanleadhinteneachanichedeachneanoagandharadhullghuirlanrmhalachnnachddhiridhn-feòirrdairneachoghasgeulsachdrach	adh
idhlichr-chlisneataineachdnnunionnsetheachreachughairthaidhùrainnthaidhlaichetheanaspraichsgthaileachdaildhadhsgachich	risdearodradhganichneachdodhuchodachòùranobhannancalhaideachrnnlairdarhadibhnnmpaullghailnnteachrricheinleandhearachidinnneachpeghidinnnichleadhleilseachadhidheanich
ear
tenichdhneamhichrbhillidhceadalheadaleannfeachinnonnmeilichneataseilteadhlachdainlaiseachdsnnmhorsairrachilrsachdabhaschfhaisganluinnmanradhsairtailnachssadhgagilterachrachdladhidhnradhthachraigrabhaschddharcigeinhleachngalusochanichdhneis	idhleadhnsaneagair	t
eanrrach
icherachdhsdailliceadanteachothainnumhanòineiamhghigochdandhanghannasachtachhth-bhailerathadealadh
idhiliroganighnigheneadhisseìnisuanìdeamtheògagmhaidhuachddachadhichnnrachgarthachidneghealtemeanneachdrethnelr-bheannadh-froisegichnsgailladhidheanthachsachdagidhidheallirfeingheagllleachleachd
achrigngteachnnnrbidheachradhichmtheinlaingsgngasbhmairpanachdnntainnrachaildhiltnsdabaidhhailtmtachdsgantharàbharachdadhraisggaidhlidhleadhgidhligeadhnnnichteichnnereagsgneachdistineteachheamladairirenasradhdachdhicheanloruslusradhsachdhichdhlgadhthèairrderrthin-riaghladhidhéidhleadhleann-spéisealachdiluailleilsdthìdeaghlearirneachdlta	chdodhlairnagr-eunghlanairreantachduninneachògairrrachhailluimmnadhradhidheachlidhreigneadhinneadhrt
achislachnrlachstusùcadhdarraicidreadhsidhrneisrlaichgabhaidhlltais	snnrdlanchdaicherharluinnemunnfanngachnibhteachlbheachinneleachgnnionnseachneamhisgeagmheachneadtirrbheiltheannealsgeaninisinnmsinnsdeegeachichltheanladirnranclandauranubanmhainnlasnailgaidnogidlrdeansdidneachridhteantheanlachrrsachttharmhorradhidhbh-chnàmhachlitiragigngluchmainnnrachgtansdagagradhidhthaneacachdashaillachgichbhanonnladhtainnnastach	dirmannanhdradhidhtanaidhn-mathgachm-chnònairrainnansdain	nradhidhnnstadigeanltmhealleagnntleachrsoiclanubanganmnaichr-inntinneachleanmhuinnshuileachadàrnalr-chunntaissanachìlòbcairedhalachpraichtanóidhhabhaidhlltais
srchdaicheharilbheachleannnmheachneadrbheegemsegeachillairnrannnoidlrdeansidneachthelachthradhidhbhaggtansdathealachichbhanladhtainn	nastach
dirmannanhradh	idhnrainnansdain
nradhidh	nntaibhmhleagruganmnaichràrr-chunntasòlaiallmhleleanneadhlach	icheanobagmachichhrraullanthasùlainnlacadhgineadnestignadhidhodhachsadhraicheadhraichnnanusadhdaicennocaissngoineuaissad	anéidheadhòirrmhorùineannnothachicheanuchàthach
adhichtesèìomhachaissand	nùisobachhainnlrgailidlelmhreas	ach
nidteachadhichrmtaradmaileadhnachasllagsighmsianachnnealobhagodadhuagachidh	eanmmachnnaichndthàdhachichidhneagsgndapasmhoréinesìdosòtaùthanuailleanlainnnachcagidheleagneachrmennachanrthàbhadhidhidsearlleachrdeachas	neachdaichradhradhèadhrdéiglleadhòrachùniabanllmhrbeachginleanionneachdheadhgeanhislbeimle-carbaidmireinruadh	ithanmeanmleidneadanhlachicheangeintinnobaglldamanrhranlamcairm-daobhrammachichhnachragradtseagtheilisirugasllaichnthasùdiglainnmsgalramnlacadhg-gàireicmneadneseachleunteigmairhsanadhidhgodhachichnmarransadhraicheacdhairraichmaicnnantanithirogsgusadhdachdòidsgmanrannicedichnnocaissgarrammachngstairùchdoc-nidhardhargichddhcnemharsngnthagachuaissadancgigmadhraidhpadtàibméidheadhidhte	achaissìbòicrionnmadhinnnaichraichmhorùineannnamhanobdhgachigeanmhnmhsthachich
eanuchàithseachthach	adhich
tefhacalsèìomhach
aissan
dnòmhansaddùissdobachirhainnrlr-athairlan-gaoithecamandadhsaggaidlnicdgeanleamlirmhntereasach	nidteachadhnsichsdidhearlagmagnanrmracailsaidtathlamrabadhhaildagngairighngnseach
gmaichlsagurthuinneadanhannachasuinnlachlachgnnmhorsidilghm-bàiseseagusaichòsódianachsaichgireanleachannnealsobhaggaglach
anmacachnùrachobandadhganachsthlachonachuagachidheangeanmmachilleamachnnaichnsgdthàcanhdandahachichrangidhneagnesgndapasmhoréidhnesìdleagmeachilochgagsachdhsionnòbancigseidmhantaóbagùandairignsgulthanu'mnagigeanlisgleanichmeasneasrdeanmeissgeachtlainnnnmachnachcagdabocleumrleumgailrneachibdheam	aidlbneacheaganmneachreanmeanseadtlmagmnnachanirraiceachpanrabancaghtsairganulthanàbairthadhidhdgidsearlleachrdeachaissneachdaichnealilearsmagnradhichradhcanlachradairh-droma	plocthaichsaidtèadhrdréiglleadhmhleagreadsgìdheadhoganmanachsganròdachileagsinnnelanachrachsaidóbhlachùdanh-Abaidhainnchdibhnengilleanrcethisg
eannelbainnnnach
ichoinenaidhtharrachaidheanchuingeanEachdraidhglais
eanlainrrachdhilean	aich
nucoiròrpaichImrichnbhenisolairemairtlllaidnadanObrachchdidhchefigearansghreachanleanaichthighlalamhspadailUachdarainisleannilesgemharrasaireanabaidrteancfhuinnhaidheandlaisdaghart	achadh
is
sanlacadhghaidhibhneicheanidildeachadhfreannghean	r
achmsirneolachgilleanmeachadh	n
nanhidheanneamhirreidhmseadganirighlingteashghearrisg
eanne	achadhris
eanllailtrummaideachdsnnanshachichrcnailmmochnamhsachlanobhardachich
eannnnngasgibhneachsgheannesnachddanisranachtachadhichtromr-a-machsaidnntairth-bheothachadhleasachadhsgrìobhadhairrrachadhidhean
icheanchuingeaneachdraidhonamaidhdar-lìon	nàiseantahgallais
eanlachaninmhntanchainnerbaillllrachinnnn
anthraicheanichginnlean	aich
nrreachdailsimpleireanuchdanoir	each	ichrachdmhorgmhaisnlaithàrròinlachisiadllrmailtraidhtas
ansgaich	reanmrichnbheichneal	anisseadhtinnobairtmadhirt
eanchaidhuidhlanradhidheannadail	ngantachnsachadh	ichuidhraicriosalseanseanantealaichuchairobairnnrachicheanchdamhibredehcheeirpirpfigearan	ilichseanghre	achandanleanach
ichthigheanrthirsinnlacnorachsanuabhasachchdair	r
ainighe	anmhnreansle	anllachicheanmhanrachsalchdibhirdheamanirgheanlceltnneagan	nigreadsbhuidhsgeachanllachadh
idheanmhmhaillrrainnmaichÀirdrainn	eachddÌnnsereÒgigehridhrainÙghdarrasanàbhachdisteachilleachdrcdeeamh
anidhghteach
annhnelachinnuinnmrachichdhnn	eachdd-eaglaissgoileachadhibhnthèadsgaidhifeachdachéibhinnfeachdachgheachinn	eachsdeachdgìmomhaigheansalreògigearheanridhlraideannndagùbhlanraidghdairr	rasanineremhallachdrachadhlairrnuighadibiachdachhadhsanllachtagnr-dheasthuathannbhailgailnnllhuillanmadiltnaichogharaidhtaissanunnsachddangachichreancdirfrinnghlbhinneachlemcheisteachdichsgleagichnidhpidhsreasanichnbheachichrgheaninneichdsgndricheachdhlannrichlslinnseadhginidhteinneachreachduinndhstitiùdobairtlagchdmhorachddhal-aoraidhlannnadhgharnadhlachirerdlagachinmadachnhguin	eachinrteanllachicherbhaidhcachchaidhnroirercuidhlagidnpachadhichdhradhideachh	eanteachllmhnadailnhidltairradhnnbharruichgantach	srnadhidhmhaissoltauinnnairidhltoirnsdrainnuinnladsachadh
idhich
teuidhtaglasraichracansicraltansbhailcallachghailluilrachmsgaidopthlannriosalseanlichtseananneachtteaglaichodhaheadhubharchairrghllagachnnraistasrpaisthaidhrnùillnaisla-bhallanbanachhairt	eachrachdhschanduinnnndairrnashargachadhnhachilidhegehesemhrigsichrignnirpheidrceachsdegeantatetheaniltmbanh-làidirsgrìobhaidhragngadaridseachadhnaichsaidnansatairochandhanghichdheanghcionnneachrscionngm-chrannransbocpachransachadhdhichrgairrrachthaicheanlteabaidhhairr-là	reiceadairlainn
nnanraichean	nnc-an-teinteinaidhnndainrngadhilrrahadhmhannadragannachtsanabaidh	lnhchdsmhuinnn-dubhainntailnnuinn
eachraggsachadh	idheanich	tennangraidhthadirnnrromsaibhidhidgeadhilheasisnibhnrgistsdeargeanulthideanleagirobhargachthargth-aonbhreac
ithcheudtaobhuaircheanneachudachadh	idhichghadairhidhmsòbcachdagintermachhannnadhróghanntamanniaghsthaichghormroidruscdeadhhgeachheiche	annneanseagteanobarnachsdatahdmaidnnpsdaraigta-postachdtachpinntirreach	adh
idh
sicheanubhair	trilthadilùgthobanachhadhrtcairrhainndachndanhainnragangaistrhuidibeanceilgearnidnearsilrceagnachsgneachteanthreachmairtbaircharhainnrnochdpairsraichn-chraoisdubhgadhphortnrachrcgadhichrsaidgadhnnunnthagiluachadhirmhoire	rrachdhadhidhemearneachreagansgtherenransgadhthaichssbchagd-aithriscleachdaidhdàimhùthchaealainfianuisimrichonnsachaidhlabhairteanmhuinnmalairtobrachriaghlaidhsiubhailtagraidheagaisguraisèisteachdaichdairhaigghaddachadhichibheanredeachgachighearseachghe-siùbhladhachdnmneachngeasisneagnachsearrgistma-lànnnndairnraigrachichecachgannsachnpardanà-arn-a-mhàireachbandganidiremhseachadhichnerigmhainnnn-fhiosainnrach-lìnicheanthachireachdèabagdghnagéideachghleagnermheassgriosinn	eachìnignomhnadhmhorradhidhtanpinnreanthòbanchrandgharineidhseamnpanùbadhchairtdagannnangachibgeanreachnasdainnlrdanth-chleasmhorma'sbachirc-leisgmeanmnaàthartallaallamhntashairlagigraicheannasraidhtalladadh-alluidhdonnruadhidhhantaoguinngadhidrle	anhanribeandeanneghdeag	neachistirstir
-sgoilellenisdirneirrbheann	achgidhstesinntirseachtirreadhthean	asslairteachclachdichnachainnndhichdragganndatachodaillidheadh	nleadseachmneachadhidhsrneseachleachl-snèimheiladchairr-rìghachthaichnragiche	anonsgallachadhbhadhrainnnntachcachdich	-shìnegadhidh	eanmorruinmsantatradhsgulladhichtamataighaichghamhuineacanaichhainnrrdarh-bhlàthailn-Beurla	Gàidhligonachrachghallasgbhagngachadhladhinnachtachireachdtainnmhairnanachairbh-chuileagganlanmnach
dndtairigrachdcachgantasuinnsadhidh	eanlrnraragach	adhntahidhichnneangeadrtillcheartearachgeagichleachnnrbhceanghelenealtealmbranaomhairuchddachadhdichraichnògirraichhabc-meanmnaanhairlaigraicheannasdadh-ruadhuinngharideanneghdeanistirstir-sgoilellennirrbheann
achsinntseachthean
as	slairt	eachlachdnachainndhichgoidheadhneachadhidhseachlrachthanraiche
ansglachadhbhadhrainn	nntachcachdichgadhidh
eansantatsladhichthaeachairdhan-Beurlaon	achlagladhnachta	ireachdtainnmhairnbh-chuileagganlanrachdsadhidheanlnrragachadhthirbhgomhairudachadh	dichranòiri-mhodhrùnthlachdadhlnnaichrsancleisleadhnteachnidhgstearan	irrealachdodaln-chànainnanachid	eachnnaichsarersdeegneach
adhil
dichthichnaoithanochdhailnilteillachdhidh	eanltairnadailhidh	eanrairtsachgailnthachadh
ilichucighleannlean	rmenealntirrichinnladachlachichrantairsgàganranileidnreachladaireandamnranrachsthair	eilrèilnnrleachichìleteanneachadh
idhichogachrbhuileachsanthlachdròdharineteachichnar-shluaghachdóirranùchinrneachrthadhi-fhortanachiomchuidhlaghailmhodh	ailnàdurrariaghailtùnshealbhachthlachdabadhdanrhgaillladhtamhailnnachadhichrsanclceaneagrtisleadhnteachnganachdicionndhgstear
anirrealachdnobhadhdalhoirglaransgn-chànainnaneòlachachideach
nnaichtanrtalsarganuinntagrceane-chathagachichrsdeegeachrimean-deargneach	adh
il	dichtearthearichleanùghairnaoithanàobainnchdthrathdhailngachnulribealnleadghreleanneisrearteillachdhidheanlachdtairnadailh-frìthgharhdhidheansrsgmhurrairltachdbhacheghathtairrsachgailnradhthachadh	idh
lichnru'mncaggharnicfheoildheseghlceanneachgnnidichinnleanrionteagfheoilmenealsachgichillghin
nneteirrgheadhichinnsealnginnlachagdachnrtclachich	eantnarndarancachlachgnuinnrachtachdirsachgantachnàbdaroggairnranidheanseargeanleidlereachneall-dubhadaireandamnasranrachlarachsadhsanthaireilrèagnanaichrsadhigeanlneilneadairrleachichthéilleagìleidhteanneachadh	idhichobhailgachl-chumhaichlrbhuil
eachunsachnthlachdrseachleanòdhargidneteachichrneaslltairnar-mhiannshluaghachdlachchuislanachdnantharóidrer-thirailnùchdanghadhignnteachdreneachseagnnlochrlagsganuinntanhadhn-AranthairrEileinUachdarainabhallcairhanaichrasdhart	asanghaidhideachadhmheilgnemsirndeoinmeanregeadidheachdmtnealsthrismashachnailmoibhneassnachdrranthairrrachadhchuingeaneachdraidhonamaidhglaisr-thuathbsarainnileaninucoirdachòlaissiarmadraidhtas
annntinnobairtmcharnndrainnsuidhobairidhirpghreachdleanaichspadaluachdarainnigheanllsleanllaicheanidheleridhrrainnàireamhightemhgharrachinneachdéiginnrighsdeachdìosalreòigerlraideandughùbhlanghdarrasanidhnemhlachdrnuigha'nschdidheachdansgtheasllmnodhamhidheamh	ninmhnearmhachadh	dnarsgarsgaidhtarhairrachicheaneachdachadhichmhnuidnntagpaicin
nragtachadhichmhorsgaidimhrto-airidhchiontacholtachrìochnacheisimeileachdichfhaicsinneachoirmeilghlanàbhaisteachininaganiulachòilneannachni'saltacoitindeangheanmhorssetheanrùcochdadhidhtedadhhaigeanrllaigrrathaistuadarrahachaidhichigrllanrrantasimhirllnnàbaidheanuidhduirrrachilemhdean	silrdeichseantaneachtinnmhaidrsagèamhaidhrahdimhpìosòinstairobaidhrnnrachadhidhicheancarhd-cheàrnachamhnaròinrasdahailrfrailghaluidhibreachadhichechedeachashcheeamirpirpfigeachr	anilrichseangheamionnachreachan
dangl-thighbheumeanachichlteilthigh	eanneachrbhcheasfeidnneperethirsinneachrtricteagirlanncaslabharmhmhailnnagaidchonfhadhoirrachraganirganmsara-sanisthasadhgncachrachramagnadhichpadaillangirnthailnrpabcaiddhadhlidhirirreagnl-chlachleartmteasndealnealsetearpinrilisseilseangtllamairnnalnradhgraf	ancasdagraisttansgadhnmunnthadheabarraichcachdhichdh	eanllachgachidnasnrluinns-eaglaisachanntasairenachdgtaicghinnlearsachidrigstear	ìrleartneagntealrcealleidigillteaghirseagllicrasailucagrdagsairòdarhacaididhirlteassgtllannalragraf
anraistsgadhnthadheacachdhichdh
eanllachnasnrsachanntataicleirrceallteagucagrianlleadhnntostalseachtutharlaidenaidntaosgocsguicàighsdobuillllcaileasaidheantaicsteanllngailrtst-dealainachdraiseasiobadhnnsa
baillansonnadhàmhìneobhaideachmh-oifisachasansainn	ach
ichseanilògraimm	aniseactiluingeanrtstnndtadhnanàganachigheadhlliunpear	-naidheachd	an-naidheachdirrceanteachadhiss	nich
eansdeanrantanlamaideachnrastrananéinìobair	eachdnnsanòcaidgnairrsadhidhdaianrtagbhinncealgeadhheannididhligleadhnnentobarcachidghaidllachisteraidrabhuicdhstalphenaichseachgtutharailùglabcaiddhadhibeandesmnaideangaidntaosgth-lìneadhagrtsgtidghoisgòdariadachhramonastairutocdadhhaisgicsgartaichubairraichcasicdeachmabaissndrainntadhàighsdtùchireanmrobuillllachcaileasaidheantaicsteanllagireannachcgailrtairst-dealainachdrabcasinnseagseachonanpsachganteachansarnachthaliamghigobadhidnnsa	-fuadain	baillansobhaidstcachghaninntseachnasgnadhsgdalpanachsnaichtaighaisdàbalrcaisdhainnmhìneichobhaideachmh-oifisachasannnsasainnach	ich	nseanilògraimmaniseactilubullcaiddhariceandsengeanneagnachseanrtsiontlagidhncaildnandtainnrgadairoiridpaidhsurrstadhgnanhagràganachidhneachasgheadhlliunpear-naidheachdan
-naidheachdirrceanteachadhissnich	eansdeanteaglaissprantanlamaid
eachnrastrananéa-chearcinreisìcobaireachd
nllnullchanrbhuicsanòcaidgireagantearnaidhrrsadhidhdaùcicrleaglasrlagtra-dorchabhadhidhnrtdcadalhidnshadhinnmaiddanuisdainnharcgaichrhadhnridhlichneachpseanthneachmachdairirsghlairngoirnandairsachadh
idheanichtachdirogichdneteanrtearachdnpachsthad-iarainnidean-iarainnleabhairtchdachdil	ssmharraichngnachgsachdgachthic-fhollaiseacheadairhmhetheodhadhthairtubadhinnrlachdanl-iùiltairmailsantabaidiabhachgchaidlaiddhghail	t
eachnltais
sannladhidhean	rmhnadaireanichlrachadhich	tesailglachladhpachlachtradhtachnachs	anbeagheiddealheirgheilnnnneadhobchdachadhidhichdagfannachpailpliss-santealtheisdumsatha-sanùo-chléireachinnleachdailnbairharsdcaildachidhghainn	eannachadhichidleansgmhepenneanteseagthleanlamaghadibhnnmpangairnachpsadgtacalhdhlhachuadh-bhocdhonnaggadhidhgmhsheantaillleachneachsmhairpaistharbairhacansdanhagailgadhidrhaiceandeashilleadhtearidhgearsheachdninnsinn	eachdnnsesteachhilmachpulltaidhharachàbachcailndhichddeilsenigteachheilmhachdirnaichpachsandaillthanèidioéicdheachdleanleigmrsdeimeidteach	adh
idh	dichìbhinngh-chathairinnnichoghachd
anillachdnnmhachdhreadhsòbcaisshddgairibceachdneagseadlgeultlaistmachhannpachnramsùbailcanhanddanhagnrachichinteansgtemn-chléireachdìomhairachadhichrraichsalgadhtachdnhansabaidhaldsairullcaichhasandgairtrtidealtaheansegeanhdeareadlleartemmirnnsealthlacharichnnnnldairmtairtmhachilnnnlachadhdhichnachannradhidhuilnnplairuillllnasanntachichobh-chràbhadhaidhdaichghaillta
chibhirneasreasdheanleadhidhsinnretearr-thoileachadhnachdsathairrachichpairheirtheabhachgidchadinndamhnaruin
eanlachnadhrandhgalhlachbhadairgichngairladh	-tìreidh
eantainnmanrlanhaslachragsann-ghillemhaighdeanachasdhgarireanchaidhsfhacalganmhairn-sgeulspradairoirbhant
angadhmonachadh	ichrachgsanachsamhgairnnmhach
dticealhedhirlbhcheageachrgeisdear	irleannneadairribhpealinrbheis
eaniseachceanileanmeilsealachsdeananrinreachochlantalthuchddlaichmarlannainnsardaràrròcandgidl-maraadair
eachdhidh	eantachdmarraicheanrsachanichgabagistellrdhdainnrtachfairgilcleasnnealirpeanreachgneachteilteachlagdlaismalhainnnnradhogileadhidhte	achdmearilthachpadhradhidhbhlaidtheachagdaichlblagpmhnnpunagigeachsillcearraeasidmsepmhlenmnidhrthulach	d
anichenachòciliablmhachilnthalaichn	achbeachidhdeillbheagiglinnmmilearnnobagirlltalachadhdargairlambhagancmalairnn-shuiladhrdradhttrteantheachgiolurdanùcanhangannachrsadhthadhlabhartimmhadhradhuinneamhasobhtgairòbachidiamachtobhagùrachongaidàibèaptairìmeachobchgidleamr	achd
nirteanmnneilrmtichlbtadhnnsairprthrabachiregallideaggngtthaileabdailgachmhailngtaidhubhchnachiachbhinndobtuirsailtachanhobhagagillubigeantàbachilleadhstlìobhadairean
h	idhean
nneantedanòbanùdadhidh
eanrthanuabadhnibgeisnseachnchdaillgaidilearsrtlanachmragràileadhnneadhnteachrdeagneachlainnlanradhichrlaidthachnèanimheachdthéilennidhthìobalnabhagansreilthichòdidrnanrùdillearrdtlanmanrrhabaidhalcdgairtrtighdearllacharinnnntairtmhachillachadhdhichradhidhuilnasanntachichodghaill	taileadhrer-thoileachadhnachdsathairrach	icheachdnarnadhdhghlachbhaich	ngairladhidheantainnnachasirchaidh	sfhacalgmhairnrbhantangadhmonachadh
ichsamhgairmhachdidlbhgleannneadairrbheiseaniseachceilmsean	aninoudlanòidladairhidh
eantachdmarraicheanrsachaniabadhnndnarrleadhmplidhnegilten-seanairesir	eanreodnnachrraidhmstamreadhtheannubhaillùbhlachcairrillabhraidhcraichdidghtearodachdhtageaghiabhsaidgeanheannneanochdsocinneadhtearachduaghighgadhigàinte	ilnéibhteanìobmòighnaidheadhmsaileachd	auadhàigmhthadinnìomho-ùrachaidhcairhair	eanrach	adhichilleir
eachadhserbheachadhilichsgeul
achtheachicheanlairrachadhuissnasraidhracdagantheangthanuthanàbhideanéinòinelnuaicheantasmhneachsneadhrce	asrachsthadhbhach	asidheachadhidheannnanich
telleanmpeirridhenndachsbaint
eachàbhail	t
eachdladhileanteanrmhachchairrachadhichsachadhich	tethèimhéideadhìdeneadhobhaltadalachadhichmhornrruidhstheiliche
anòbhrachghailisealtalasnrachadhich
teùbailte
achddhghradhileanlardiabadhirnnhasrachunnchairdnanrranachadhsnadhtagbhsecearirleadhpidhteach	dmidlearleagplidhneubhargilten-seanairesire	anreachdobaghaglachdgachidlacgachlmlachnadhnach	anachichsarprradhidhmachdsartamantareadhistteagheannionnignnrrichubhailllacgnasthadhùbhlachcairrdadhilrsach	dlabhagancarraidhcanhdraichdhagigeadhgidearghtearmstmanodachdhightearppachraichtagneabhagghmacairhannach	ichuinnuchdiabhchdairsadidthbistgeanheaninneachneachnneanochdpsseaganneachocdinneadhtearachdsirpiùgachuaghighsdirreadhsaidgadhnigàibnteillnaighearpachéibhteangeilsneadhìobgachmòcanighmachdachadhich	ldlagnoineachadhidhichtinnrachgeachandairneachlachlachrailileachuraichnòirnrachórachiardgeadhodanlamusrailtachùrodallamasuainichteanreansgaidiglctàdgilladhidhádèidògùcairndagnidrneanrachsachnagaireachdn-daraichrraidheadair
hmodhidhseanmanachpsaichldaeachdadhiceanghodanhachigeastraichuadhàgachilnigmhaichrthadinnìomhaicheòdo-dhèantaùrachaidhbhrachcairhaireanrachdrachadhichdaglnrgailnidealtanghneasleasgheasleasir	e
achadhdsemeachneannionnrbheachadhil	sichsgeul	achinntheachmhicheanlairrachadh
idhlainuissmaltahnasnpraidhchanspadagirlhadhga-da-ghliogchlainnuinnideilsear
achdlpeanilriseachtsdearngnoillrsanthalteachdladairgtrrachillreachguclairradairniacdeaglnlgeanigeanocaidlgnnadhtagradail	nidsradhrissnichetheaglangaideadhanuchdiachdugtùcanhanigochllngranracanthracadhiceildheadhnganigeilhllsneachodòchandiodochdgaillnnnantuanidhleachleachseiltheanéidhùdanuaicingrsellrsanàgachlaisinrnlrdanréiclreadseilìdocachirhannsradhòcgltrsailùidsearllnnlltrabhardcdaganideanghmhnnointenaissthairneamachdhngthaichnothadhrtiandeagngleanutobadhghalluabnitthadhilnladhàbhideanimeachdéinòinelnólùbthladhtabhaiccdadhhadhidhirghirlcngpealririchneanachseachneachtlanclachdachdhmagighnaichngarranartoignnrumpaglaichullrachdbhanach	tacachr-fhiacailshuileacheachdhainnfaglladhrillnleud-eachàirnrnainlòcrniallcdeanghocachrapclagnachupùbhardidioreadh	gicheanradairobhcaidhnn	eanidhlemrmeanilpthrabaidicghlichngairthaireafanpthudpòdagianachopacholamaspachuctair
eanr	ail
nidhear
s	illlmpaidthàcairniceillle	adhèapaidìochdghachpachtheilòdhicdhùthanuadhicmmachdidearragrdthaignàbhachulldagideillinnrneilteanmpntahèarnalisean	anéidheachadhich
telleachìcdgmnleagobullgmpeanòbhiridhteldapraissanùchdichdrtrruabagcaniceanheantaslmhneach
sneadhprceasteachannachrachassthadhbhachasilcchddganicdheachadhidheannnanich	telbhirleanmeilnnpeirreidhelchartmhormagichdnnrnaisnagdachtpailrragm-suainsbaint	eachthainnàbaidhadairilt	e
achdladhcramaidibhirreasleanteanmherlmhachchairrachadhichdailsachadhichtethachèabmhnarpairimhéideadhleannsdeachtìdelicheneadhteagobailnhaltachaintrdagachlachadhdhgichmhortamannpunnrruidhstheiliche	anupòbhaidhrachghailisealtalachissachnrachadhich	ternóbhrachgùbailte	achdhagdhganhradhiceanl-chritheanstthlairmhailrdailsdalt-Abastolingealmtelbannachltanmarodannnadhidhranmth-leasachadhachirrrachadhEachrballrachnnsbuigileanudachòinIarlasgachleachochdnadgantachucharObifigear	irllamhSabaidhalgairtrtlainnmmhainnradh	idhoghail	lirrsaealbhgairnnicrbheisseaninulaòladairmarionnach	ichrraidh	mthùcairligeheuaghighànaighearoillsesgeulluisradagthuthàidònuainipeirltainàbaidileanUanile-chumhachdachleamsgerramach	ichsabairthallsadhstolchdrasdhartasghaidhineolach
sgealidhmeachadhhidhigrgeadiodmseagtehrislltantmadanideachdrshrannamrtmochobhardachnngaisnach	ddhtar-a-machanbhairrmsaltarth-leasachadhairrrachadh
icheaneachdar-dhealachadh	lìon	theangachadhradhgalllachrballsarachdhsbhuidhtharileaninsimpleirudgnòlasrnafhogharianrannraidhtassadgachich	rnnealnobairtdhalghnadhmairtlllanpachadhradhmhnadgantasnadhmhasnsachadhseanubharchairùlobairchdamhghaibrefigear	irghreleanachlacaslamhsanpadalsabaidhalgartighdeareadllainnmhachilladhradh	idhnasoghail	libhreasdhrrsathaireachd	amh	nar	uindhghlbhgairladh	idhmragnachasdhchaidh
sfhacalmhairnrbhantamonragsamhichelgnneadairrbheis	iseachcseaninudlamarlanòidladhidhtachdmarrsaiabannnarleadhonnach	ichsarrraidh
m	machdstamristtheannigrubhail	lùcairillabhraidhitteaghiabhgeheochdocuaghighganàinteòighneachd
aighàmhthadobhrachchairilleireachdserbheachadhsgeultheachlarachadhuissnnraidhradagthaireathianuthàbhidòinlntoidhlereuputhìthuaimhneasnnachidheachadhidhnnmnnpeirridheàcramaidilelréisdìdelodaltarthòbhrachlaisùbailteachdghiluachdar
aninereadairllachmhasnsalbhalghidheamachadhlesge-beathallachadhrramachsÀitemrdthÒbang-mhìosrandughàbhachdistghileanreachmht'-obrachelmrainneachdcandachadhmunnéideadhidhìmomhaighòganachigeachrirlachrainndughsdairtrachùghdairr	rasirsgeulrlarabaidhachinnrtlnnaichrtais	s
ancaidnrshairtsrtais	s
ansdradhisssadhaillgairhadhidh	eanrmnradhichedh	eanibhsean	ridseceildheamfeidgeish-tasgaidhòsdaeadais
sn	-tasgaidh
òsdalichlceaseasbartgneachdmrichpmhlisgneadgealachdilistearneamhprbeartheartachingireneachdseinniosgsgeinleasmsbean	adh
idheandealealangeadanlichtheasginnneachslachichntemhlaidmaichhaidhnnmhasgladhullnaichlachcardnasgobh-beòilclìùildeaseiginntuathandhairlghasibhdgmsnichtearmadhnsgnadhp-dubhadhgidhrelachrachairidnbh-nathrachachcuisgadhideanrradhmachan-dépragidngnguingsuinntanrmhorsdangadhidhtaidhhaichunneabaidchd-a-steachair
eachdannsaicheandalachhairraichgairsgmhrsgairhlachicheanmhachllachidmhaidhrllpuillllnacadhchairgadhirnachadhichtachdrbcmannsgrsachadhichrgdamgibideachcheadhneòlais
sdidhlinnleachnenteanricgnnsimeans-meadhonmeidteanasanlebhiseangthuchddgmhailmòmachdódhhabhainnrtnnrtasancahair	tsrtasandradhisssadhaillghadhidheanradhichedh
eanibhse	anceilgeish-tasgaidheadaiss	n
-tasgaidhòsdangealachdilrbhegneachdseinnissbean
adhidheangtinnneach	slamhlamhaidh	nnmhasgnaichobhanistearmadhpaidhradibhnnmgaid	eanraingnguingsuinntasgadhidhtareabchd-a-steachaireachdnsaicheangaisgmhsghlach	icheanmhachllachngairnachadhichrbrsach	adhirgdicheadhneòlaissnerignnmeansteanasanlebhiseanthudmòmaiamhaidhdsear	angeadhheanrn
aninnlgeadhilleadhmchealliollnneas	anisocaideandhlac
adhmnadhnaillndadh	idhsgalach	nadhrammachadhichtaughlachdmhoràthobarhtacharradhsaiddhargailrtlachicheanrrachradhighl-inntinneach
asich	telnntermeasgteilseachgealteanll-dhubhadhmanbacahaissultnnanrachdhrachsdraidiseantangeabhadhsisubhan	sdnasòirrachadhidhichiallncleantaoblaideanùirodighmsguaghighell	eadh	idhsissadhdarganàghadhighlleilthéigsinnìòcair	eachuaileasreamgneadhrasdalthanachas
ichbaist	eanhairtdgadhibhnnhadhigeseachinnlleadhteanmneachadhdhichnteamlchannmadhnnaganradhraigmanuisssaàbhachdileasgleabh	rmhnigrladhidhmailthachdrladhmaichrtarèarainteachdnadhéidìdemreanòirseach
adhidhich	easnrradhùirlingrsachsiachairdhanmhaidhrmailbirtdsearangeadhheanrn	a
n
silnnlgeadhilleadhidhmchealliollnneasanisobacaideandhlac	adhlampmadhichnnadhichtepansachnaillnaildadhidhscainngainn	lachnadhpramcmachadhichsgtsantatugainnhaichrrlachdmhorusailàmthsìgheachdnùthobanrhatachailrradhsaiddanharlairgailrtlachich
eanrrachhaidhlainnradhsaidibheumchiosdalgheachl-inntinneach	asichtelteannachinnmhseachan	nnisgneamhterbheartmeasgisg	teneichteprcheassgianteilseachgealteanhbheumlgl-dhubhadhmm-sheanganadnbacahaissultnnagnrachdhnachcanhairrghanmanrachunnsdgairtaltahrabhachiltchdadhladhdhidiseantalletmailtngodghnapansdanachgadheabhachasdhchailghaidlaichsbhaidhlannnsadachgibhireachsseginnodhairubhachn	tassdn-ri-treunastasòirrachadh
idhich
eichiallairnthcdleantalseannnseariroblaid
eanuailnaidubhaschanthachùcairirobhaddgbhoilichdhgheanleismhepemaichnbaidhadinnmparaidsdailngtuacanta
sghighelleadhidhsdairilleachmeadnnsearspsadhdarganthairàghadhighlleilth-saailèalamhn-ri-trèanéigsinnìdleachanleachanòcaireachidhtùpuaghichealleastnealigreab	adhmpgneadhisgeulneag	rsdtheallaigrasdal
aichsaidgailthanachas	ichbaisteannhailtdangadhideannnhadhgigseachinnlisleadhidhteanmhseadhneach	adh
sdhichneasachidhreadhnnsglingsesleachdhichteamaslachgichchainnnnuis	eachgmadhnagnachadhgansgadhradhgmancaisguinlachsochrabandhgigmanturuissachdsathagnàbarhachdirnrnachstalcharandhileasgleabhrmhnigreilneanachgsealanladhidhnntanfuinnmailteachhachdnaisterladhidhmachadh	nichusnachdairrsanthèachdrainnte
achdmannunnnadhruinnéidsìdemorailreanòbairtchdiceilrleumseach	adh
idh	dichnrachdradhùchanirlingseachsrailnsachstuabairtharsachchdairrain	nibhreach	sdhgheanneachsllmhnefheoilneartpereadairnnaniginnibhsleanichthllachich	eanm-sahagrrasachunnnachparachsaillthab-abagidhrthalcashd-mhacachdéideadhachdabacillanharganhsaibehirdheamachadhd	ichte	nimirgheamaichnillce-bheistchumhachdachichannrleanntmmepenicionnneagannigseannpearinnrceaneachandsbhuidhghiollidhghollachsgsgeilulseagge-beathaachanichliginnnntlachangidhrtaichbhachfhartaichlachadhidheangichmhaichtachmadibhnnmhaillpaidhngnsaradhraidhballcaghairllrsgoidlaradhilmnnsmachichsaireannsainnsaidgarpagirnntagaichhardraidÉirinnÒg-mhìosÙrachaidhnuigheanàbhacashdisteachrandhmhorghachmhoricheadhidhgeachhleadhnrgheasleachdgansidhneanrtaichichrcdeileachanmhanidhghneachgissteachadh	is	n	sgnhneichdhlachichnnuinnmhgarharuinnraidhnartrachrachaissdhichdhnneachdcand-bheannchomhairledoruseaglaissbuiginntinneachsgoil
ethainistearigh-oileinachadhibhchnachlasochmunnossaidhuinnsranuigngntháèadladhidhrrsgaidh	eachdifeachdachéibheallinnleagceartdeadhidhfeachd	ach
ichegheach	dinneachneach	adh
idhreadhichdhghsdeachdrgleanteadhgighìcmnnleachd
achnseochdaranganmhaigh	eansaltadhresbeanleachadhichòbanganachlachifiggeachrirheanridhnidnseachrdeheircleachsglachmarnrachdragideanicheannsnaichedagnughichsdairtrachùbhlanraiddaillaichedhrathadghdairrrais	s
anidhglleadhneichrdeliosneissgeulsmaidhhallachdlaghpaidhnlaghpagrachadhichrlabhairtchichmrmhasnnrnuighuisgtagnhraids