Malawiaakulung'onobalaetizidweomaukusawenziraerezeretsedweinochepeteichitakhulupiriroondiristuulirelengedwenyamatapanganoembedzozesomotaeirewawaokeratsaumadabadwatizidwaerekawerachilitsidwamwata	nsoira	tsaikanakalibenahalazikitsaozaulupiriraomananzaeratuumanabukirapatsawanilitsalakhulamulirandirakhulansoirapaembangapheraitsikaolangosolajezaseratawandipatsayankhaenaeraionaekeratsa	erajezeraongapachikidwambanangatsidwaempha	erareka
nso	edwazaekahedwaunzira
tsaidwaitairira
zaonyedwaukitsazidwarawaitanalangizaengaumbirirapatsauzayambairankhaenerasailesiyezabalawera
nso	e
rae
tsazerachita	iraotsafaikaunakhala
mo	itsaululukira
piriraulapatsanitsogolerawaniritsalamulirandiraekhulaekangaotamangidwasulidwavawakonena	njieraonaekeratseraongedwapitaulumukatsaidwasiyaonkhanitsatengahedwatsaipatsasegulidwaikaukaeitsa
idwawerengauza
idwaonongayambankhaenerazindikiraeidzodzekotengapowaeðafaeikaeiraeunairatsitsasirajakachitedachitakhalazabweransokhalafaunagwirekhalaumudwalandireemberaibembeiranepatuleuonongevaenathaemanapolothetseswirizindikireehalabeemoiratezikitseidwaomozansorisitutuululukirepiriraenguomanendazekereiubadwawera	nsoetsachifunata	chitaira
eniokaeradalitsenadauliraikirawalazitchawa	pofaikaotokozaufuzanafunairatsitsasaganizawanaonawairaitsaidwa	zanaimirakhala	beudzidwalupiriraomananzaekeraulankhulamanatsogoleralalikirambiraulirankhulabeeemabangezapheraingaliraraonjezawau-akuluakulumikizanamasulidwaudzitsogoleravaeratsawambaeranamadichitiraenajakaonaekaratsa	e
raepangazotsanieembedzapheranyererareka
nsozaekahaunzira
tsaitilizarira
zasanthulainthaonkhanitsawaungatanthauzaerohamangandizeipatsatsimikiziraogolerauzasikamikizairaogolerautsa
naumikiraukitsidwavomerezawaliraonaerengaonayambaikirankha	eenda	yendaeraerasaetsazifunandikirawanilitseidwaeritseidwetsalalikimulira	endiraegizikhula	epeembaedwa	eekezekendogaezipheratsazaibekounena	erambikitsidweoyonazogalirasoporaiwonseyenseongojezawaeumikizanem'maderaloabadwaerekaukuweraetsachimwatachaira	tsaokeradaliraikirayazitchawazimbaitsafanana	itsasoikairaunafunasaganiza	irawanawairaitsaidwaraikakambanahala	beiraonzazaudza
nalupiriraomanandaoukondanilapatsawaniritsaiyalakalakalikirambiraulirandilira	rakhulaembaoekezangapheraolaedwanjezowaumikizanamatirapatsavaeratsera
tsawalirandikondapatsaenagawaeidweofunakhalathaonaekaeraratsa	erapangatsaempheranyaererareka	edwazahaunzira
tsaitailizabesamala	irangalalathulaintha	idwaokeretsaonezamphenyankhanayezawaungatanthauzachedwaula	idwansoengarohandizaipatsatetezasogolerauzasatairaimikiziraogolerautsa
naumikiraza	idwavomerezaulazambulutsawakondatchayambang'anirakha	ulaembekezaeranda	yendaera	tsarekezasaetsaizindikiraonatengabalairi-mbirimbiriuyeenewaoyouðaithengaimaundukatiodziyophamvuumphuingotimasogoloukehudzelulukirelandiranaothandizeveraetserawaliranabadwairatizidwawelaerarachimwaritsatairanji	tsaokaeradabwalitsawalayazaiperekafaeraikaunasaidwaganiza	irawiritsa	zanaikapoidwatanakambirananawapezahalazikitsaulupiriraondazauchitiramanapatsaniweralalikiramulandirakhulaembaedwa	rangaezapheraidinsoraiolangosolajezaserawamkwezalandiratengaukhazikalandiraonaukitsazayankhavawalirainondikondayankhaenaelerakayamulaonaekeratsa	erapachikidwangaidwatsaidwaempha	eranyarekazaekahedwaunzitsaidwawanyaitailirariraonyaedwaulumutsasankhaintha	idwayaonyezatayaikaengarohaetsaokozaiferakondalengansopatsaulumutsasataimikizairaulukamizaukaitsidwalandirambazairidwawaitanalonjezapatsahaunzitsatsimikiziraeruzidwaonajezerayamba	sondikizitsakha	ulaendayendaerarekezasaetsaizindikirapangawadaleendeichotserapatsa	ehunzitseenaeraig'onoafikireunegwire	ire
tsekhale	ireumane	sulenithandizeninenepezekeothetsereipulumutsethandizeelowirojikachita	iradziwaganizasungatchedwahanzaonziosembetchitohambiuwaouyamatangazakeongaothuwoonaetsereongekepaderazikomwambangasitsaidweemphaerorekaezaekaehedwainduunguzira	etsa
e
iitaeiriza	eoulumuketsidwesachitedakhaleyambekhalelandireowenabadwetizidwewerechokefikekweremwaliregulukekhaethula	eutayikeitheilamuikalintheyaungatachimwatadzangokhalathauzatehauyambaendaikechutchutchuengaerohaeokozaunthupiwoikhululukirepatsaethandizesogolereuzasataireegulaeimikiza
ireogolera
ipanoulukemikirewiufululamuliroelemererouulumunthuzaimuwapatseirionongeyambaenijanensokhaendeeransosedwaizauzimuichitadaziwitsidwakhalalankhulaoledwamayindikira
eonapempherasangalaloðiribaibulongajalositaodzakosimandogoukhuliuliongweliosawalonjienziranieraniinochabewinoceheikhumiristuulu	rulendosanutatuikawirikacholeehala	pooudyamanja	zereverawanjaphatiwaniritsidwalamanjazerebirioyophamvuuyayangauwirouzerupaderautalathaupisopanoukolerezimuwozoonaeni-chenichenichoteibalechitikeokeradachitikaliniperekedwayambawizachitikae	okafikakhalaewaniritsidwaloiwitsoðitsoodzofukwamundoiroopigawoololoheberimajakakamizolatayikirohalaeidwe	ra
ezikitsoozaristuulukiro	lukiro	piriraoombo
-khumbo
khumboipirirookandanoiwererozekero	rouchitikagwirizanaoneka	tsaperekedwazekathandizawaniritsoiziolakolakomulongizookhuloemabondogedwereichonselimbikitsonsoolezomboungamomabwera
etsachokeradzakehalaudzanaulalizironenagaokhalaonekapezekaosasulirothandizaiyambazindikirikaenechi
oodzi	-modzinso	modzinsowemwe
chinachokerakhalalipatsaonyedwayidipitirireunjienerogakhaleereziwejokaosinsiombathunziyengopanganotasoembedzozekehunzitsochoindariroululumutsorisamalirongalalokhouzoutsowawainsiokonezomonitathauetezohandizounzi
-thunzi
thunziionthozosanzoimeikizotsimutsoogolo	zoulotsano	oukukowalitsiroowaemburengerouziro	o
chiindiriyambi	reikonijanitso
okhuloembekezoneraretsoozindikiritsoooloweziunguzoochepaitaika	tsaokerafunadaika	iraimirirapakanahacholaudza
nambaomachonakondagolawanira
itsalakwandirirakhulidwaemberaetsangedwapheratsaedwaingaowamalizavetsawechi	o
nsonchiodeenezagaseyansa
choengaonadiekaratsapambanandagidwapatizaerekazekahimbaosasafalepherangalatsathaekavutainthikayanaokonezekanyezawaekataniyikachingaereotezerahandizaekaisatiraimikizikarizavalautayambairiraenerazamaizwitsaumaitukukodalandaulogaengaraindiropatimentioongosolozakanjaidzidzikolionalothuwaniuloenansowoi-enieniwofanizooodyaukolumbinadogosaolopigalimotouniziranioloyuwoolidiululioichitikeofejakadakhalayendehalaeozaubwerachitikafikaotokozaunagwirakhudzaonetsapezekasinthawakhudzayakaendaeraliporiyonseomachitaika	rafikaunansogwiraitsidwa	zanakhalaudzanauthandizanilimbikitsamveranenaonekaeratseraperekasowathandizayambaendaeneyinsoofairiraniodzinachitikafikairalimangidwansotiyambaikaidediensoyogakhalepoounsoritatuhaiwensoyoirionsowaoyendeerasoiozinsoojugakabukukawinocheteilendositatuidwewiriumadalifukufukuguluwiridwetsidwekang'onoehalidweulidwelalikinkhulidwetaekalemberaikonsemamangidwetipatsabaenezedweodzinayiemaothawiuupangidweembedzedwenansohikidweunzitsidweolosamalidwenutatuhuisopanowiriunduwiri-kawirikawiriyaendetsedwezembeenakakelikonseohalaniidwemaunsalateolomaosizaristuulupiriranimboingutuodabwitsaizodzedwafananaunikairakatiyesahalaudzanawaniralimbaokomabelizanososotuitiwekolansepambanitsandaeosasakhulupirikalekezathaekavutataniengedwareohandizaekaratuivutayambaenerazamaizwitsaubadwansolatizaidwawelaeraransoeratsazabwereza
nsozera	etsansoedwachaedwapetsazaichitagawolamuloitsa
idwamenewairapanganotalaindaululuritsa
idwataidwaka	eratsazaokaeratsaedwaulukadabwaitsachitikalira	nandauliraonekaikirairawalayaedwazachitikafikakhalaololauthandizaninjasoonaekapembedzaulumutsaterohazaidwaeraichepetsadalirazimutsikakhululukiraondawezaletsaumikizitsaonaetserapatuliraerekahaulumutsasiyanitsatchaengerasutsawanayesaðaodzaedwafalitsananaiziraikapoiraotokozaufuza	nsokulanafunadogatiraidwaikairatsitsasaitsaoganizairawanairaonanawairairatsa
idwarazanaitsaikapoidwamabafailirarirakachitadakhalagwirakamizidwahalaomananzeraukonzeranilimbikitsaowambairananapempherazasambatsegulawerengahalabekomonsopoeirazikitsaidwaosizaudza	naidwalulukidwarapiraikarambaudwazaomanandawaereratsagolazansoedwaka	eraperauchitikadalitsalapaimbikitsanimanabukiraonetsapatsa
niulumutsanitanthauzahandizanisogoleraukazaniyankhaendazaindikirawanilitsaidwaritsaidwatsatiranaerazaiyalabadirakalakawairalikairambiraulairandaidwalaragizidwakhulanasopo
idwapawaedzerakanambakoedwaraekezarangansoedwazapheratsaedwazaibensochepetsakonseliramabana
koika	itsanangalila
ranapiraorayeretsaolaerandolagosolajezatawanaezaukamikizanam'chitiramawaabwera	etsachimota	ikaokeratsaderazulofananizaunafunaikasa	oganiza
owirakambiranahalaozalankhulaembaizaokowamvandagansoiriraokhalalingalirajazereonaekaongapaziempha
erarekatosanthulaomphenyaukalaidwa	ratchedwaendageransohandizaetsaipatsasitsimutsayamba	iriroikombabaliukira
niyoenekoyanaedwazairazaidwakanizaotoyopandogatsahamvutundaudalirazikanahulupiriraonda	weretsalandiraolanjezamvaerandaonatsatirauzavaekaranatsaera	tsanawamba	kozaeranagwalibemavekapezekadikhulupiriralimbikitsapanda	gatsahunzitsathandizasogoleraenaeragakhalethandizeofikirakhalasiyazindikirajairakaositchitohakawiyadanjaengaedwazimiraumbazeruonanasoekaeraraeratsaedwa	ra	tsajezerakhetsaongaedwa	kapachikidwambanandagaikizikatasaidwaukanala	poidwaembedza
eraphaera
eranyaererarekaedwawazamopoekaðahanatikizapoedwarezeraunzira	tsaidwawanyairiratairira	zatsaonyasaeraulumutsaidwamaitsaulayolaerasakahulupiriralabadiramalaidwa	ra	tsabaverangalala
tsaidwakhathulansoutsikaweruzikailirandikizaidwajiriratha	ku	nsoikayanaitsaokonekera	za
ekankhana
itsaidwayezawaekaukulungaidwathatawatalinthauzaidwalidwarayachedwaraula	poembenukangapoedwaratharotezaedwa	rahamanganadizana
idwathauzawaedwakangotsaokozaupiichotseraferakhululukiralimbikitsapatsaulumutsatengelahandizasogolerauzaonthola	zasalataidwaraegulaimikizaidwalikaratsimutsaogolera	o
koutsa	naidwa	kaulukatsamaikirazaukansoiratsalutsamabikairirazazaimuvomerezawachitadziwitsalaimbikitsamasulavetsaonaetserapangatsaembedzerapharekaulumutsasungatenga	erahandizasatiraimikizirauzawaongolerazaindikiraerenga	edwa
rauza	naidwaonaetsaongayalambansoiraikairandikirag'ana
irajanakhaulaembekezerandayendaeratsaerarekezatsa	edwasayesaedwaraeratsazamaitsa	idwaichitadziwakhalaonzawaniritsalankhulaembaingalirandikiraikaonasinthatsataziyezaungulirazaidwakaðerengawabwinocheitikawirikehalaoukulurutimbiriphumphuuyayangathunthuukoopaderaezekathunthusopanoulerewoyandikiraeni-kwenikwenizainalabwinocheinayisanutatuetezerowiriyankhulokehalaumiougonakhalamwambapembedzatiwanulikulurung'onomanjazerebalioyophamvuulolinthundiranigaliizowirokhondoula	nisembeupaderamlungutimaulungungidwaisilierekedwathulipisopanowoekanimbanieranini-lenilenirolinoichitiradalembedwaionongazachokerakhalayatsidwafejakambasahaleozauchita	irafotokozagwira	itsidwalongosolaunenaonetserasinthatchedwaitsogolerasimikiziravomerezalilonsemeporionsemabwera	etsafikagaðidwawira	ira
tsaidwakambahalaudzanenaonekaperekazaekahunzitsasonyezatanthauzachaeroipatsauzaenelioriodzinsonachokerakwaniritsidwalembedwaionsosokonezayambaenagalirotheoopengaritanthauzahandiza
eeiuzawuyeneraofananaikaotokozaunafunaikairagosiwiritsaimirapalikambahalaoonzekaudza	naomandagolalandiraiembaedwaekezedwamalizavekawelionamaenajezanoosepandatsidwaulikalierekaedwazahunzitsaosasafunamalairaemaindikizidwayanaungatanithauzachedwaeretezedwahandizaiosatiraitsimutsaogoleravutayambalielandaeraraumbironthapangam'badwoibulolenjaukhuusayochakaifanizokalatahalidweoulupiriroondilungamopanganoembedzoindaululuyanjanodalitsonieralioierekezizanjaikomonagulukabukuchisimphindiwamabukhuungwederazimoganizoziuluikokhalidweutulemboreowandajapaziempherosikuomphenyauwauyikobaliiriuyoenemoimbapingotimayoyozindaodzitoyoudzindasizituwambazindendeondomekogelojirakhanithawiyanjaengoumbathamboupisogoloulozakainenerothupindaochitikanseabaibulolanjaodzamaukhuuwongwewaloenzichaputalailitsomoritsotachitaidwedalitsondauloeraziwoulofanizooukomundegulosowa	opatagalimotonizo	wowoziuluweroiridweikonaka-makalatamakapanindaiwohalaidweotiinaolomonosiumingwaituwanilitsidwelambeulo	wongizokhulidweekezerombaedweongailimengalilo
ronapiroreoondajezano	otowaumbirongomembalailiyoniunanambaladaenogawajakhwalaothazereofesindoekedwepangidweziempheropalatohunziroiriulaniogalamusabatalimoombaunautsozandeeloweroðeroikuomphenyawophenyaukulungatanthauzirooendawahedwesokawautsanoupiudindofumulamuliroendoosimbonithengaumikivesiumbulutsotowailesiuyankhoendedweseroikonazanamazanaikobadwolameeindeenderairioniukhusayeozichakaifanizokondipanganoululuyanjanodalitsonieralioierekezimazikonafulumundogulotigwirizanoikangohalidwelanduiriyoniungumbapandotaherezeroingosamphaomalinkhanozitengoimasinjeunduyalambaondaendozioyozereimuyokachisi	mokamwanganootei-katikatiziyoulinganauruwawatibwiiyolalikindugiziembinga-lengalengaingoungumadziganizoululondajasikuowabuyoenemoodziyoundatuwambanenerigelojirakhanithawiyanjaumbazakeongawoeruodabwitsaekhazichepetsadalirazimutsaperekafananaulumiraganiziraonawirizanakakamizahalaulupirikaondwaerawaniraezalembaimbangaliranaraondolamaliziratusukavekawemonsonsonamagansoiong'onayengaonaekera
tujezerapandaitasadaliralekezambedwamomalaira	tsatsatiravutayeneraemphanaiyanataniereohandizanaiosatiraimikizandikautsanayambang'anaeneraraowozamapakanamvundaotahambuuvutsoepoziindiugoulupulumphunozirotsiingoraulumutsimuloweyasamphanagamsangaeriwuonkhanotandawoenderegohupiimasikananjeogolerio	moulomikiwindauuchakaikhalidweulupiriroteyanjanodaonaerayambazakhala
elandiramtumikirapezasungathazeeikomowaekakhalembiranenganotiyanjanehalaeozaululukirapiriraondaudziwafunalankhulaumikizanaonapembedzazahatikizaunziratisegulawerengalamulirendireukhuleembeibekufunangoosiwaungumachitafunaganizokhalaondalemba	ootoitimapingotendereimavetsenachitikalionjezapenyadandandaendeikumbukirepatseondomekoenegaganizirekhalireodwepezetheolankhulajiraothawiuyoonaesankhaetitengereiyeiungaetengehaeupiikhululukirepulumutseuuzimuyambayaenerawachangueteindunjisinsisawawaonitsanzodalazidzi
dziikakehalaonzeka
eraufunakhalatiyalamulondiraembambaophamvusangatendereunanansowankhosayogaoziwirojirauzeruonapaderaezahunzirasankhaonkhanitsatchutchutchuhusatanetsataneokapanoufulukatswirilerezimuwoyambaizieraziinaizakaimuyondawoonsen'chakutiifukwayanikofunikalotanizimeneofunikaipathekaachodyazakhalaiperekafalikiraeikaikaidwakatsegulahalaolandiraowambalakungwisongolevawaliranenagauonaekaerasoperekazaitaonyedwaumulasankhathulatengaedwaisataumikiraukansozirawalingaliratanthauziraerengaonsoyambaensoozingaonsochifukwatoyanidakatulohalazikitsalamandirakhulaekambapherandandaenaionaperekazahunzirawaphunzitsaerengayambaekhamangandeichifukwataeira
eodachitaikakanahalalembaionapemphazahunzirauzidwayambaenerazabweransochitakhalaupatsa
umulitsanilandiraowathiraiperekaewaekachitethahalaeozaulupiriraosathandizaubwerachitadikiraziwafotokozauna
funaganizawira
itsazanakambiranahalamo	zikitsaulupiriraomananzaupatsanilandira	khulaembapheraimbikitsaumikizanamenevaetseranenaonaetseraongapatsaniemphanieraeranya
ererarekazahunziratsasankha	thulainthaonkhanitsawatanthauzaetezahainsopatsauzaniwapatsaerengaonongayambaembekezerandazindikiraonalandirekhulaeniiolenitiwemachitadzifunsafuna	saganizawira
itsakhala
idweozaulupiriraondaukondanilembamvetseraonapemphaerarekaza	ekahunzitsasiyathawerengayambazindikiratengaeoyonakhalauikalimvanenaonapatsaenya
ererazaitatsalaenaegakhaleirepambanethe
tseresoupamenensoereka	ezehunzireitaonsoritathaerohuumizileniwaeoyambaendaeraotanizakutiichitandikiraeofunikathekaondomekogakhale	nsoletinsoongoleziwiroinjijalairayoziokakhalambangonizawazaokwendoyapesayoumbaniwaliyoofunika	irasathekavutathekavutayeneraulakwatiwataniokhansesaluembeingaombatchitoyohakambinowiyiozoðiyoendaitiyoumwinthuyalimayongajaengoyeziimboumbazabwinokethueruikaothekaochepaerailitsamwawataikaraokeraulukadabwitsanawalazafaniziralaichepetsadalirafunirakondaperekawaodzedwafananaerasiotokozaufuzanagatiridwaikairatsitsagawaonawiraitsazanaimapajambulakalambambanahalamowoudzanaidwalupirikaratitsidwazaomandanaedwawagolazekawaniratiranalakwambiraulirandirakhulidwaekanitsidwambaedwaerangaedwazedwaimbanganaolanderaolajezedwawaungamamalizawangirirasukairavekaratserawenamaninsoditsogoleraenatsetsa
nigaokondasewaoyengaonaekatsaongapambanandagidwatsidwaulika	itsaitsaembedzarekaedwazaekahedwaunziratsa
idwaitairiraosasachedwaperaitadziwafaunakhalaulupiriraonzekalankhulaekambedwaungamamalitsaverankatengainsosutsikaukayendaeraraemainthayana-siyanasiyanaonyezaungira	kotanichedwaraelombenukangareotezedwawarahamangandizairiraionthozasalawotanairailizariza	waogolerautsanaikauziridwawawaeruzayambairirang'ana	iraelandaereratsaeraerarapachakaudyaeifukwamakeenepatayambinjanookhadakalilibeerazakhalanjaikofunikapi-fupipafupifupipafupigulukadalilimawapitatikatiehaleomooubweransodzafaunakhalalingaliramvaonapembedzateroisatiralibensongasoponseokhamafunikakhalalopazietosikuotendawabaliuyoenensopaoisonkhanolingounguodizimwetoyopandohumitandaimaulanduungutuwambanalembedwaibeyeneradekhag'onoakhalenoozijirakhaniondookhapasipotchitohakawi	yi
oðiuyanjaumbapepalazekahiriradaisotaliengahupiisambaidwakuliogoloulendowekhairioyekhapayekhaneraokhazakaifukwameneembedzerophaniera	nionadai-penipenipalarekahangalitaziinduriunziloro	litsaniwandoitaochitaokeratsaulukafanizitsaikairaotokozaufuzanaganizairawanaonawirairatsakambirananahalapokhazikitsaudzanaonzawanilitsalambirandirakhulaembangaimbanangalirathandizaolawaumikizanamalizangapanotsaweponenaseyengeleraonaeratsapandagaenyererarekazahunzitsasachedwapalemekezamalirankhathulaonkhanitsaungaterotezahandizaetsaiuzasatairairizautsanawauzaerengayambaira	irandikirag'anaendaetsaraekedzasedwatsaulaniezidentiogalamusabadwatadaliphunzireyambezachitafunalowaðaonaulakaiwafunakhalansoozaulupiriraudziwafunagwiramvazindikirawalankhulaepheraimachitagwiritsalingaliramvasinthathanabadwedziwekondwererelemekezedwaengeimvereonekepezedwathegakhalethethulanitanahayansieneraikoyeneraukhalatanthauzahekaiwabwinolikhalalingathematheroudziwakalowahalalinachitegathenalidichitaokadalilimonachiteligakhale	theyambag'angapadzakhalansokhalatifunakhalauonamayongakhale	wanitsetero	heriyenerayanazichitikakhalautanthauzayendaliritanthauzaudzakhalansoonongekakululingafenitachitakelandiraembaingaliranenaerathauzotayaeyambazilembacheruikamoloutchutchuelefoniombererongarohambondizoziekangoumbapiibwererechitaedakhalazikitsalindauliranepezayambazachitafakhalawatulidwamuonaonapezahunzirasanthulayambaendazidwaeikhalawafulumizanenagatirekadakhalakhalepemphazetheihalaeiraozaulupiriraeondaweretsezekereubwerachitadzaiwafikauna	funagatiraikagwira	itsa
zanakhalaulupiriraumanalamulidwankhulaeimbanangalirambukirevaonaerapempha
eraeranyererazahunziratsidwaitasanthulathawerengayankhaembekezerandazindikiraonalandireembaeeleibembikengalireoleniumikizanamabukuchita	iradziwafikaunaganiza
irauluwiritsakhalaozaulupiriraondazekeralandirakhulaepheraowamvangeolankhulaonaetserapempherazaekathaulutsayambaenerasetsazionanabatizidwachimwakonzalienagakhalenenephunzireireteroheipangaemphaerazamoehunzira
e	tsidwerisadayambekhalelakwenthuleinthetayehamangeesatireyambeembekezeranelaraizichitakhalandikiraeonaperekezionetseraokhansesambankhoutanetsanetaneikuliondetsiogolokanopanoubaletizowanaenzirereinochidakwagawengamotaeiredachitaokeralembailiponiyambaindozafaikaunsakhalalalikidwamulirandiramutchaonapezahwanyaulumukasungathaeipenyererarekefaulumunsejakakhaleomanalambandireiopandaolothandizeezindikirehalaeiraozaulupiriraomauchitaokadikiraziperekawafikaunafunaganizirawiraitsakhalaulupiriraomanaulalankhulaembapheraingaliraowaunenaonapempha	eraerarekazahunziraitirizarusanthulainthaowaungathaiwazindikiraerengayambaendazindikiraonawatierazelalikiomulirondirekhuleelembereelelororaeroundopherereibemingaliresopowonseolesiulumabwerera	tsachitaikaokeradzafunaganizakhala	be	poiraozaondalandiraembaumikizanamvaonapenyererazekahunziratengahandizayambaendaretsabonienewouodziyophawiumphuulungunthuvetsewanaininachitika
iraokeraliowamasulidwapachikidwatidekhandeenerigakhalireomaneposethesatirewiroozikaonaepangiroemphere
rerekezaehunguziraiteosadayambekhalenakhethuleikuwonthayetatechimoengehengawo	uisaliraiogoleriutsanaulukemikiwapempheerengeouyambenkheendeeraseozichitalembamundikireonevesiliumbulutsolotowabodzamawerainocheteibaledwifumundokhalireristuondilungamomwemwepembedzosanuomotatuwiriokeratsadindidwaikalesikalembaehalandazikitsauminguoubalachita	iranidzaiwa	itsafaunakhalaulupiriralitsamvawambanyumbaonetsapambanatsahaimbasinthatisutsayang'analandirakhulaembaeraoleranjezawamaliremunanthabandairikatiziuluruoyophamuvuumphutenderegounthuuzayayawamunandipatsag'onoaokhalawirojikhanzaosaurusanjeembetchitohuuyengedwazeruonaetsapaderafupingaidwatalisidwaerekaedwazahamvuinduunziraitaulumutsidwasankhatayaerohanziupiikonzeralangizapatsauzasikirauopanoumauchidakwamokaliulurumulungunthutalizimuwoyambandikirazaindikiraekhani-weniwenirenganiinansowakeobadwachedwakerapaeraimwatachitaokeratsaulukadabwaitsa
idwalairaikazalaichepetsakuzalamuliraperekawayeretsaodzedwafananaikaunaikatsitsakakalalambahalakozikitsaetsedwaudzaidwalupirikaratitsidwaomaetsedwerandaedwawowagolazaeka	eraperawanira	itsatsidwaeraiyalakwalikirambiraulirandairakhulaembaedwarangaedwazaolanjezedwayowaumikizanangamamalizasukaizaveratsawensonamadipatsaenaezagaseyadaengaonaekaeragokapambanandagidwatsaidwaulikaembedza
erapherarekazekaeraturahunziraitaosasachimwafaunakhalaulupiriraondwamalaira	tsangalala
tsaoneka
yothautsainthikayanaowaungatangwanikaichedwaraengareotezedwa	kahamangaikondayoonthola	zasimikizikarizaogolerautsaikawalaeruzayakambaira	irang'aniraelambekezerandaetsaeraerarasedwayabweretsainocheikhristunayitatuetezosulowiriondedabwitsazikoikulurung'onotalikaleloehalaoudikirafaganizakhalaonzansolengamapetoukaonaphasinthaowatimakononjazerebaniiriotoyophamvutengounduuyayangaijikhouopaderamwambayokhaerekedwathaupisopanowoyikuluekhamwensoyondanii-yeniyeniseretsaniimenenansoochepaitairatsaokeraulukafananaotokozaufuzanaikairasaganizairaonanayiwirairatsa
idwazanakambiranahalairazikitsiraonzekaudzalupirikaomangolazaekerarawaniralakwalikiramulirandirakhulaembaedwarangatsaimbaondolagosokaweraumikizana
itsidwamalizavekaweyonsonenagaseonaetserapambanandagairatsaidwaempherarekaedwazerahedwaunzirira	tsaitaitsaosasamalairanthulaonekathavutaeindikizairathairayana	siyanaonkhanitsirawatanichedwaerehamangandizaetsaeraisatira
youtsawawitsaonayakambairiraendetsaeraeraraserazabodzawinocheikristulengedweungamopatalaembedzotikaukukoumakaleziehalaozoubweradyakhosilekanitsaningamwambatchirehengoupiisogoloyalaembedwaingam'mwambaakonolotophunzirobirikuwaoyophamvutsogolouyayanadaleithandizagajikhalangotchitohuuopaderazikofupimwambansitsidwaezekaitazoosachedwapasinthairaokonezekathanziupisopanouchimozimuwozikuluruedingaizeniichitidweka	eokeradabweretsachitikadililiperekedwazachitikadifikakhala
iretha	ndizaithandizafukwanirogawengaokayendahalaeidweozaulupiriromboomouchitikairaokeragwirizanakhudzalankhulidwaowau-zikuluzikulunenaoneka	eratsa
edwapezekasintha
iratanthauzanjihandizaniyenda	eraerawangwaniilitsidwei-zikwizikwilakolakonkhuloembedwa
eilingirireniporizonsemabweretsachita	ikairaokerafikaunaikagwira	ira
tsidwa
zanakhala	iraudzanauthandizalalikiraembedwanenaonekatsa
eraongapangaerekasonyezaulidwatenga	erahandizaipatsauzasimikizirawakhudzayenda	eraeraerasedwa	tsaenezioodziutsogolerenachitikadiokerafikalandiraembedwanga	edwairiperekaonyedwasinthayambaendaidikira
nithandizeg'onoadetsepothandizeeiwathandizeosinsithuzioyansiraonekaera	etsaeroongapangizotalasoembedzohiphiritsounzitsozitsoririzonsesadachitikekwanilitsidweyambengalalokhouoniyezatanthauzanjithauerohandiza
eekeunzi	thunziithandizesambanzovomeziwalondairiziyankhuloenelarazichitikaokerakhalandikirooloweziðiriochepaimwatachitaika
chitikaratsaokeraulukadabwitsafananaufuzanaikairaipakambiranaha-zokhalazikitsaokhaomanzekaudza	nambaudwitsazanaololamanandweretsagolazerapaerawanairaezalabadirakwaitsangizakhula
idwaembalembaedwaziraeratsangaedwapheratsaimbanaikitsangalirapiriraondolaumikizanangamamalizangaidwaraeravekawezonamaenagasezioyansaengaonadiekaeratserajezeraongapandagidwatulikaemphaedwa	reranyekarekaedwazaekaraosaerasacheperafunikakhalamalirangalatsaulutsathuliraonekathaekavutayeneraemphanaindikizirathayana	-siyana	siyanaokoneza
ekankhanitsirawaekaðatanielezingerarezioohandizaekatseraitsogoleraonthozasatira
ziimikizikaraogolerautsanavalautawalawazoitsayambazoira	iraendaeraeraraserazekarazamaizwitsa